### PR TITLE
Extend Signals Section with more topics

### PR DESCRIPTION
**Pull request by ritwik12**
Topics:
- Signal Groups: realtime and standard signals.
- Signal Overview
- improved few terms and sentences

### CODE REVIEW

**Comment by ritwik12** [comment]
@stormic-nomad-nishant @kalyanceg Can you please take a look?

**Comment by sumeshpremraj** [comment]
Looks good, thanks @ritwik12 
@kalyanceg shall we merge this?

**Comment by ritwik12** [comment]
@sumeshpremraj Yep. please go ahead.

**Comment by ritwik12** [comment]
@kalyanceg Yearly ping 😅

**Review by sumeshpremraj — APPROVED** [review]

**Comment by pylixm** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Pull request merged**
